### ISSUE TITLE
WHMCS to BoxBilling

### ISSUE THREAD

**Issue by fossxplorer** [shyaminayesh/boxbilling-to-whmcs#1]
Possible to get a script other way around?

**Comment by shyaminayesh** [comment]
it's created long ago, if you can explain little bit may be I can make something better :dancers:

**Comment by fossxplorer** [comment]
Sorry for not being clear @shyaminayesh 
What we need is a script to migrate over from a WHMCS system to Boxbilling. I'm willing to test as i have a production site running on WHMCS atm. Thank you very much!
