### ISSUE TITLE
Migrate all the stuff

### ISSUE THREAD

**Issue by josenobile** [shyaminayesh/boxbilling-to-whmcs#2]
Hello, would be great if we add:

Orders
Invoices
Products
Products addons
Product promotions
Tickets
Knowledgebase
Servers
Hosting Plans

Do you have understanding of database structure of WHMCS? I can help to program de scripts to migrate.

**Comment by shyaminayesh** [comment]
@josenobile ugh ... it's just my fun project :) if u like I can provide details :)

**Comment by josenobile** [comment]
Yes, please!

**Comment by shyaminayesh** [comment]
@josenobile check your gmail inbox :)
