### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by lukapaunovic** [shyaminayesh/boxbilling-to-whmcs#3]
Does the script still work?

**Comment by shyaminayesh** [comment]
not sure. need to check again

**Comment by lukapaunovic** [comment]
By the time you responded I have written the script myself which is using APIs of BoxBilling and WHMCS and transferring clients + invoices :D 
I was thinking about proceeding to products/services but I was unable because WHMCS doesn't have all necessary API calls. weirdly, boxbilling has.

**Comment by shyaminayesh** [comment]
I abandon this project because I made my own billing system. :)

seems like BB have some extra API endpoints :o

**Comment by lukapaunovic** [comment]
Yeah, I was surprised. I mean I wasn't excepting that lack of WHMCS API functions would prevent me from completing the job only using APIs.
And I really can't mess with MySQL as I do not have that amount of time.
I'm gonna publish what i've done so far. It would help someone for sure.

https://github.com/lukapaunovic/boxbilling-to-whmcs-migration
